name: docs_pages_workflow

on:
  push:
    branches: [ master ]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install -U sphinx-rtd-theme
          python -m pip install -U pygame
          python -m pip install -U numpy
      
      - name: make the sphinx docs
        run: |
          make -C docs clean
          make -C docs html
      
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/build/html
          git init
          touch .nojekyll
          git add -A 
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -m "deploy"
      
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
